### ISSUE TITLE
[CONTRACTS] - TODO before deployment of Bonding V2 in front end user interface

### ISSUE THREAD

**Issue by zgorizzo69** [ubiquity/ubiquity-dollar#122]
* get BondingShare V2
get IDs based on address (one address can have several bonding share ID
```javascript
const ids = await bondingShareV2.holderTokens(
      myAddress
    );
 let bondingShare: {
    minter: string;
    lpFirstDeposited: BigNumber;
    creationBlock: BigNumber;
    lpRewardDebt: BigNumber;
    endBlock: BigNumber;
    lpAmount: BigNumber;
  };
// endblock is the blocknumber at which the lock period ends
// lpAmount is the remaining LP that sits on the bonding contract for that bondingshare
    bondingShare = await bondingShareV2.getBond(ids[0]);
```

- you can check how many ExtraLPrewards you are entitled to

```
  const pendingLpRewards = await bondingV2.pendingLpRewards(ids[0]);
```
you can't withdraw it is automatically distributed when you add or remove liquidity
NB: These functions only works when the current block number is > bond. endBlock

- to deposit the first time you call the deposit function

```
bondingV2.connect(signer).deposit(amount, duration)
``` 

- to withdraw LP tokens from a bonding share (that is not locked)

```
bondingV2.connect(signer).removeLiquidity(amount, bondingShareID)
``` 

- to add LP tokens to a bonding share (that is not locked)

```
bondingV2.connect(signer).addLiquidity(amount, bondingShareID, duration)
```

**Comment by Zequez** [comment]
The idea is to create a GUI on the front end available after a member wallet is connected that exposes all these SC functionalities?

**Comment by zgorizzo69** [comment]
the idea is to modify the existing front end to use these functionalities

**Comment by zgorizzo69** [comment]
also we should check is the connected wallet address should migrate 
to do so we need to check if `toMigrateId[wallet address]` is > 0 this field is present on the BondingV2 contract 
if it is >0  then we can display a button that will trigger the migrate function  that should create a BondingShareV2 for the user

**Comment by Zequez** [comment]
So
  - Replace all the usages of bondingV1 contract with the V2 contract
  - If toMigrateId > 0 show button that triggers the BondingV2#migrate function

Just wondering, does this migrate function creates a new transaction with it's fuel usage and everything?

**Comment by zgorizzo69** [comment]
one PR for the migrate button here https://github.com/pavlovcik/uad-ui-launch/pull/4. One improvement would be to make the button display conditional if
migrateID > 0
 ` const migrateID = await bonding.toMigrateId(account.address);`

**Comment by zgorizzo69** [comment]
one PR for the bonding share adaptation to V2 here https://github.com/pavlovcik/uad-ui-launch/pull/5
now we have the shares which is the rights to mint UBQ linked to a bonding share and the LP token that are locked inside a bonding share

**Comment by 0x4007** [comment]
@zgorizzo69 @Zequez can you guys update the status of this?

**Comment by Zequez** [comment]
Part of this is implemented here https://github.com/ubiquity/uad-contracts/pull/12

The `addLiquidity` functionality isn't implemented yet, and neither is a UI for checking the `pendingLpRewards`; but we can see all the bonds, deposit, withdraw and redeem UBQ for each.
