### ISSUE TITLE
Research: Minting Zealousness

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquity-dollar#154]
@hpiyankov you expressed concerns about how our protocol may not mint fast enough with low demand. Can you spend a couple weeks on researching a solution when you're back from vacation?

cc: @ubiquity/research

**Comment by hpiyankov** [comment]
This issue is related to this one - ubiquity/ubiquity-dollar-development#123

Are we saying that we need an alternative solution to the one proposed there?
