### ISSUE TITLE
TwapOracle doesn't reflect the spot price

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/ubiquity-dollar#299]
The problem with twaporalce we've already experienced is that it couldn't reflect the spot price even if we call `update` function manually.

Originally discussed in group chat.

**Comment by hashedMae** [comment]
It gets the Time Weighted Average Price (TWAP) which is different from spot price. A feature for getting spot price would be best suited for a contract separate from TWAPOracle to avoid confusion.

**Comment by 0xcodercrane** [comment]
What I mean by `reflect the spot price` is that `current balances` is not included in the math. TWAP price is absolutely different from spot price. 
To get the spot price, we can simply call `get_virtual_price `of `MetaPool`.
Thanks for your consideration @hashedMae . Right now we built the twapOracle on top of curve twap theory.

**Comment by pavlovcik** [comment]
Sorry but the purpose of this issue isn't clear to me then. As @hashedMae says, the TWAPOracle.sol contract shouldn't deal with spot price. 

As @0xcodercrane says, the metapool shares the spot price (we already get both TWAP and spot prices on our [dashboard](https://uad.ubq.fi))

What is the benefit of including the spot price on the TWAP oracle?

**Comment by 0xcodercrane** [comment]
If I clarify about `spot price` 

1/ The spot price @0xcodercrane  was saying is `current balances`, which isn't actual spot price.
2/ The spot price @hashedMae was saying is the actual spot price we can get from `MetaPool` directly

**Comment by pavlovcik** [comment]
Current balances, I presume, can be queried from the metapool contract. Why would you make a copy of this logic on the TWAPOracle?

**Comment by 0xcodercrane** [comment]
I don't think I understand you're saying. can you clarify which logic we're copying?

Our twaporacle has been implemented as described in curve twap oracle theory.
Based on curve theory, we need 2 balances map (first balances and last balances) and time duration.
Right now, we don't use current balances for last balances which is also recommended by curve.

**Comment by pavlovcik** [comment]
So the TWAPOracle is incorrectly implemented as of now?

**Comment by 0xcodercrane** [comment]
Thats correctly implemented based on curve twap theory.
