### ISSUE TITLE
APY Calculation

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquity-dollar#4]
I think we should use our [uAD-UBQ Sushiswap market](https://etherscan.io/address/0x41e087485f47538752a1195d984109cb8dc0e429) as the oracle to calculate UBQ rewards APY.

**Comment by Zequez** [comment]
Quick question; is that market address documented somewhere? The SushiSwap link from the dashboard goes to `https://app.sushi.com/swap?inputCurrency=0x4e38D89362f7e5db0096CE44ebD021c3962aA9a0&outputCurrency=0x0F644658510c95CB46955e55D7BA9DDa9E9fBEc6` which has the correct pair, but doesn't reference the contract address you linked.

On the [contracts Notion documentation](https://www.notion.so/ubiquitydao/Smart-Contracts-dcc417a31d21414c8b70d6bd6e99fd71) there is a link to the ["SushiSwap pool" contract](https://etherscan.io/address/0x534ac94F198F1fef0aDC45227A2185C7cE8d75dC); which to my confusion, is not the contract you are mentioning. What is the relationship between the two?

**Comment by Zequez** [comment]
We can close this after that branch is merged.
