### ISSUE TITLE
Clarify Withdraw Shares Explaination

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquity-dollar#9]
![image](https://user-images.githubusercontent.com/4975670/133130812-2bc49255-142b-462f-8af7-daa56ee1b29b.png)
> why doesn't my staked LP tokens show up?
> it says i have 0 bonding shares
> 0 that are withdrawable
> but perhaps we should adjust this to be more clear

**Comment by Zequez** [comment]
I've got the code to show this figured out from the vfat work, so it should be easy enough to implement it here
